name: Build and Publish

on:
  push:
    branches: [ "test-pipeline" ]
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          # server-id: ossrh
          # server-username: OSSRH_USERNAME
          # server-password: OSSRH_PASSWORD

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build project
        run: mvn clean install

      # - name: Publish to Maven
      #   run: mvn clean deploy --settings .github/maven-settings.xml
      #   env:
      #     OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
